"use client";

import { Plane, Users, Fuel, Hotel, Car, Utensils, Phone, MapPin, FileText, Printer, Download, Mail, Route } from "lucide-react";
import { flights } from "../../data/flights";
import type { FlightLeg } from "../../types/flight";

export default function TripSheet() {
  const flight = flights[0];
  return (
    <div className="grid grid-cols-1 xl:grid-cols-[1fr_360px] gap-5">
      <section id="trip-sheet" className="bg-white rounded-3xl border border-slate-200 shadow-sm p-5 md:p-8 print:shadow-none print:border-none print:rounded-none">
        <div className="flex flex-wrap items-start justify-between gap-5 border-b border-slate-200 pb-6 mb-6"><div><p className="text-sm uppercase font-bold text-[#007DB8]">Williams International</p><h1 className="text-3xl md:text-4xl font-bold text-slate-900">Flight Department Trip Sheet</h1><p className="text-slate-500 mt-2">Passenger details, crew details, and FBO/fuel details are separated by leg.</p></div>{flight.ownerOnboard && <div className="text-right"><div className="inline-flex bg-[#062A55] text-white rounded-full px-5 py-3 font-bold text-xl gap-2 items-center"><span className="text-amber-400">★</span> GGW</div><p className="text-sm text-slate-500 mt-3">GGW Onboard</p></div>}</div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><Summary icon={Plane} label="Aircraft" value={`${flight.aircraft.tail} · ${flight.aircraft.model}`} /><Summary icon={MapPin} label="Route" value={`${flight.route.from} → ${flight.route.to}`} /><Summary icon={Users} label="Passengers" value={`${flight.passengers.length}`} /></div>
        <div className="space-y-5">{flight.legs.map((leg, index) => <LegSheet key={leg.id} leg={leg} index={index} />)}</div>
        <div className="mt-8 border-t border-slate-200 pt-5 text-xs text-slate-400">Draft operational trip sheet. Final operational release should be reviewed by authorized flight department personnel.</div>
      </section>
      <aside className="space-y-5 print:hidden"><section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6"><h2 className="text-xl font-bold text-slate-900">Trip Sheet Actions</h2><p className="text-sm text-slate-500 mt-2">This page is print-ready now. Native PDF file generation can be wired in later.</p><button onClick={() => window.print()} className="mt-5 w-full rounded-xl bg-[#0066D6] text-white px-5 py-3 font-bold flex items-center justify-center gap-2"><Printer size={18} /> Print / Save as PDF</button><button onClick={() => window.print()} className="mt-3 w-full rounded-xl border border-slate-200 px-5 py-3 font-bold flex items-center justify-center gap-2"><Download size={18} /> Download PDF</button><button className="mt-3 w-full rounded-xl border border-slate-200 px-5 py-3 font-bold flex items-center justify-center gap-2"><Mail size={18} /> Email Trip Sheet</button></section></aside>
    </div>
  );
}

function LegSheet({ leg, index }: { leg: FlightLeg; index: number }) {
  return (
    <details open={index === 0} className="rounded-3xl border border-slate-200 p-5"><summary className="cursor-pointer text-xl font-bold text-slate-900">Leg {index + 1}: {leg.from} → {leg.to}</summary><div className="mt-5 space-y-5">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-3 rounded-2xl bg-slate-50 p-4"><Info label="From" value={leg.from} /><Info label="To" value={leg.to} /><Info label="Depart" value={leg.departureTime} /><Info label="Arrive" value={leg.arrivalTime || "TBD"} /></div>
      <AccordionSection title="FBO / Fuel"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><ServiceCard icon={Fuel} title="FBO" primary={leg.fbo?.name || "Not assigned"} secondary={`${leg.fbo?.location || ""}${leg.fbo?.phone ? ` · ${leg.fbo.phone}` : ""}`} /><ServiceCard icon={Fuel} title="Fuel" primary={leg.fuel?.name || "Not assigned"} secondary={`${leg.fuel?.location || ""}${leg.fuel?.phone ? ` · ${leg.fuel.phone}` : ""}`} /></div></AccordionSection>
      <AccordionSection title="Passenger Information" defaultOpen><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{(leg.passengers || []).map((p) => <ServiceCard key={p} icon={Users} title={p === "GGW" ? "GGW" : "Passenger"} primary={p === "GGW" ? "★ GGW" : p} secondary="Passenger manifest" />)}<ServiceCard icon={Hotel} title="Passenger Hotel" primary={leg.passengerHotel?.name || "Not assigned"} secondary={leg.passengerHotel?.location || ""} /><ServiceCard icon={Car} title="Passenger Car" primary={leg.passengerCar?.name || "Not assigned"} secondary={leg.passengerCar?.location || ""} /><ServiceCard icon={Utensils} title="Passenger Catering" primary={leg.passengerCatering?.name || "Not assigned"} secondary={leg.passengerCatering?.notes || leg.passengerCatering?.location || ""} /><ServiceCard icon={FileText} title="Passenger Notes" primary={leg.passengerNotes || "No notes"} secondary="" /></div></AccordionSection>
      <AccordionSection title="Flight Crew"><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{(leg.crew || []).map((c) => <ServiceCard key={c} icon={Users} title="Crew" primary={c} secondary="Flight crew" />)}<ServiceCard icon={Hotel} title="Crew Hotel" primary={leg.crewHotel?.name || "Not assigned"} secondary={leg.crewHotel?.location || ""} /><ServiceCard icon={Car} title="Crew Car" primary={leg.crewCar?.name || "Not assigned"} secondary={leg.crewCar?.location || ""} /><ServiceCard icon={Utensils} title="Crew Catering" primary={leg.crewCatering?.name || "Not assigned"} secondary={leg.crewCatering?.notes || leg.crewCatering?.location || ""} /><ServiceCard icon={FileText} title="Crew Notes" primary={leg.crewNotes || "No notes"} secondary="" /></div></AccordionSection>
    </div></details>
  );
}
function AccordionSection({ title, children, defaultOpen = false }: { title: string; children: React.ReactNode; defaultOpen?: boolean }) { return <details open={defaultOpen} className="rounded-3xl border border-slate-200 p-5"><summary className="cursor-pointer text-lg font-bold text-slate-900">{title}</summary><div className="mt-5">{children}</div></details>; }
function Summary({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 p-4"><Icon size={20} className="text-[#0066D6] mb-2" /><p className="text-xs uppercase font-bold text-slate-400">{label}</p><p className="font-bold text-slate-900 mt-1">{value}</p></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs uppercase font-bold text-slate-400">{label}</p><p className="font-bold text-slate-900">{value}</p></div>; }
function ServiceCard({ icon: Icon, title, primary, secondary }: { icon: React.ElementType; title: string; primary: string; secondary: string }) { return <div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center gap-2 mb-3"><Icon size={19} className="text-[#0066D6]" /><h3 className="font-bold text-slate-900">{title}</h3></div><p className="font-bold text-slate-800">{primary}</p>{secondary && <p className="text-sm text-slate-500 mt-1">{secondary}</p>}</div>; }
